---
# Install Nginx
- name: Ensure Nginx is installed
  yum:
    name: nginx
    state: present
  become: yes  # Ensure the task runs with sudo/root privileges

# Ensure Nginx is enabled and started
- name: Ensure Nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

# Deploy Nginx configuration file
- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

# Ensure the Nginx configuration is valid
- name: Validate Nginx configuration
  command: nginx -t
  register: nginx_config_test
  changed_when: false
  failed_when: nginx_config_test.rc != 0

# Create a directory for the website (optional)
- name: Create website root directory
  file:
    path: /usr/share/nginx/html/my_website
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  become: yes

# Deploy index.html (optional)
- name: Deploy website index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/my_website/index.html
    owner: nginx
    group: nginx
    mode: '0644'
  become: yes
