---
- name: update web, nfs, and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark (yum)
      yum:
        name: wireshark
        state: removed
      when: ansible_os_family == "RedHat"

    - name: delete wireshark (apt)
      apt:
        name: wireshark
        state: absent
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark (apt)
      apt:
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
