---
- name: Deploy php-todo application from Artifactory
  hosts: all
  vars:
    artifact_url: "http://54.196.86.61:8081/artifactory/todo-dev-local/php-todo{{ build_number }}/php-todo.zip"  # Customize the URL as per your structure
    deploy_path: "/var/www/php-todo"
  tasks:
    - name: Download artifact from Artifactory
      get_url:
        url: "{{ artifact_url }}"
        dest: "/tmp/php-todo.zip"
        headers:
          Authorization: "Basic {{ lookup('env', 'ARTIFACTORY_API_KEY') }}"  # Use your API key or Basic Auth token if required
      register: download_artifact
      failed_when: download_artifact.status != 200
      retries: 3
      delay: 10
      timeout: 300

    - name: Unzip artifact to deployment directory
      unarchive:
        src: "/tmp/php-todo.zip"
        dest: "{{ deploy_path }}"
        remote_src: yes

    - name: Set permissions for the deployed files
      file:
        path: "{{ deploy_path }}"
        mode: '0755'
        recurse: yes

    - name: Restart PHP-FPM service
      service:
        name: php-fpm
        state: restarted

    - name: Clean up the downloaded zip file
      file:
        path: "/tmp/php-todo.zip"
        state: absent
