---
- name: Deploying the PHP Application to Dev Environment
  become: true
  hosts: todo

  tasks:
    - name: Enable required repositories
      ansible.builtin.shell: |
        dnf install -y epel-release
        dnf install -y dnf-utils
      args:
        warn: false

    - name: Install remi and rhel repo
      ansible.builtin.yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          - http://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: yes

    - name: Enable remi-php74 repo
      ansible.builtin.shell: |
        dnf module reset php -y
        dnf module enable php:remi-7.4 -y

    - name: Install PHP and dependencies
      ansible.builtin.yum:
        name:
          - php
          - php-mysqlnd
          - php-gd
          - php-curl
          - unzip
          - php-common
          - php-mbstring
          - php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - php-json
        state: present

    # Rest of the tasks remain unchanged...

    
    - name: ensure php-fpm is started and enabled
      ansible.builtin.service:
        name: php-fpm
        state: started 
        enabled: yes

    - name: Download the artifact
      get_url:
        url: http://44.211.225.131:8081/artifactory/todo-dev-local/php-todo59/php-todo.zip
        dest: /home/ec2-user/
        url_username: admin
        url_password: Enzakuna12@21

    - name: unzip the artifacts
      ansible.builtin.unarchive:
       src: /home/ec2-user/php-todo
       dest: /home/ec2-user/
       remote_src: yes

    - name: deploy the code
      ansible.builtin.copy:
        src: /home/ec2-user/var/lib/jenkins/workspace/php-todo_main/
        dest: /var/www/html/
        force: yes
        remote_src: yes

    - name: remove nginx default page
      ansible.builtin.file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent

    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted