---
- name: Deploying the PHP Application to Dev Environment
  become: true
  hosts: todo

  tasks:
    - name: Enable EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        description: "Extra Packages for Enterprise Linux"
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

    - name: Enable Remi repository
      ansible.builtin.yum_repository:
        name: remi
        description: "Remi's RPM repository"
        baseurl: http://rpms.remirepo.net/enterprise/8/remi/$basearch/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi

    - name: Install necessary packages
      ansible.builtin.yum:
        name:
          - dnf-utils
          - httpd
          - php
          - php-mysqlnd
          - php-gd
          - php-curl
          - php-common
          - php-mbstring
          - php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - unzip  # Ensure unzip is installed
          - zip    # Include zip if required
        state: present
        enablerepo: remi

    - name: Ensure httpd service is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure php-fpm service is started and enabled
      ansible.builtin.service:
        name: php-fpm
        state: started
        enabled: yes

    - name: Download the application artifact
      ansible.builtin.get_url:
        url: http://3.88.112.68:8081/artifactory/todo-dev-local/php-todo59/php-todo.zip
        dest: /home/ec2-user/php-todo.zip
        mode: '0644'

    - name: Unzip the application artifact
      ansible.builtin.unarchive:
        src: /home/ec2-user/php-todo.zip
        dest: /home/ec2-user/
        remote_src: yes

    - name: Deploy the application to the web root
      ansible.builtin.copy:
        src: /home/ec2-user/php-todo/
        dest: /var/www/html/
        remote_src: yes

    - name: Remove the default Apache welcome page
      ansible.builtin.file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent

    - name: Restart httpd service to apply changes
      ansible.builtin.service:
        name: httpd
        state: restarted
