- name: Loadbalancers assignment
  hosts: lb
  tasks:
    - name: Import Load Balancer assignments
      import_playbook: ../static-assignments/loadbalancers.yml
      when: load_balancer_is_required
