# # ---
# # - name: Loadbalancers assignment
# #   hosts: lb
# #   tasks:
# #     - name: Check if load balancer is required
# #       set_fact:
# #         load_balancer_is_required: true  # or some condition

# #     - name: Import Load Balancer assignments
# #       include_tasks: ../static-assignments/loadbalancers.yml
# #       when: load_balancer_is_required
# # loadbalancers.yml
# - name: Assign Nginx load balancer
#   include_role:
#     name: nginx
#   when: enable_nginx_lb and load_balancer_is_required

# - name: Assign Apache load balancer
#   include_role:
#     name: apache
#   when: enable_apache_lb and load_balancer_is_required

# sites.yml
# - name: Loadbalancers assignment
#   hosts: lb
#   tasks:
#     - name: Check if load balancer is required
#       set_fact:
#         load_balancer_is_required: true  # or some condition

#     - name: Import Load Balancer assignments
#       include_tasks: ../static-assignments/loadbalancers.yml
#       when: load_balancer_is_required

---
# - name: tooling
#   import_playbook: ../static-assignments/webservers.yml

- name: todo
  import_playbook: ../static-assignments/deployment.yml

# - name: sonarqube
#   import_playbook: ../static-assignments/sonarqube.yml
